/*

    1. Guardar nombre jugador. COMPLETADO
    2. Al empezar el juego se podrá elegir jugar o introducir palabras. COMPLETADO
    3. Dar opción al usuario de introducir palabras según niveles (fácil[4 o menos], medio [de 5 a 7], difícil [7 o más]).
        3.1. Checkear que la palabra introducida sea válida (no números, no repetida y dentro del rango).
        3.2. Si la palabra es correcta, insertarla en el array indicado.
    4. Guardar datos partida (como nivel y palabra seleccionada)
    5. Método que gestione el tiempo (guardar como dato de partida).
    6. Mostrar resumen de partida.
    7. Llevar ranking de partidas almacenando el tiempo de cada partida y su dificultad
    8. (Opcional) Dibujar ahorcado
*/

//Declaraciñón de variables:
let playerName;
let optionSetWord_Play;
let wordsEasy = new Array();
let wordsMedium = new Array();
let wordsHard = new Array();

//Declaración de funciones:

function main() {
  console.log("Welcome to The Hangman Game.");

  playerName = prompt("Please, introduce your name:");

  optionSetWord_Play = optionSetWord_PlayFunction();

  if (optionSetWord_Play === "1") {
    console.log("Play!");
  } else {
    generateNewWord();
  }
}

function optionSetWord_PlayFunction() {
  let option = prompt(
    "Choose one of the following options:\n" +
      " - Type '1' to play with a random word.\n" +
      " - Type '2' to play with a word generated by your self."
  );

  do {
    if (option !== "1" && option !== "2") {
      option = prompt(
        "Error. Please, enter either '1' or '2' to proceed.\n" +
          " - Type '1' to play with a random word.\n" +
          " - Type '2' to play with a word generated by your self."
      );
    }
  } while (option !== "1" && option !== "2");

  return option;
}

function generateNewWord() {
  let option = prompt(
    "Choose one of the following options:\n" +
      " - Type '1' to enter an easy word (Max. 4 letters).\n" +
      " - Type '2' to enter a medium level word (Between 5 & 7 letters).\n" +
      " - Type '3' to enter a hard level word (7 or more letters)."
  );

  do {
    if (option !== "1" && option !== "2" && option !== "3") {
      option = prompt(
        "Error. Please, enter either '1', '2' or '3' to proceed.\n" +
          " - Type '1' to enter an easy word (Max. 4 letters).\n" +
          " - Type '2' to enter a medium level word (Between 5 & 7 letters).\n" +
          " - Type '3' to enter a hard level word (7 or more letters)."
      );
    }
  } while (option !== "1" && option !== "2" && option !== "3");

  enterWord(option);
}

function enterWord(optionNumber) {
  let introducedWord;
  let correctWord;
  let maxLengthAllowed;

  switch (optionNumber) {
    case "1":
      maxLengthAllowed = 4;
      introducedWord = prompt(
        "Introduce an easy word.\n" +
          "Remember:\n" +
          " - Maximun 4 letters long.\n" +
          " - No spaces.\n" +
          " - No numbers."
      );

      preCheckWord(introducedWord, maxLengthAllowed);
      /*---------------------------------------------ESTAMOS AQUÍ------------------------------------------------------------------------------------*/
        //Atención aqui la palabra que sale es diferente
      console.log(introducedWord);
      break;

    case "2":
      maxLengthAllowed = 7;
      introducedWord = prompt(
        "Introduce a medium word.\n" +
          "Remember:\n" +
          " - Between 5 and 7 letters long." +
          " - No spaces.\n" +
          " - No numbers."
      );

      console.log(introducedWord);
      break;

    case "3":
      maxLengthAllowed = 100;
      introducedWord = prompt(
        "Introduce a hard word.\n" +
          "Remember:\n" +
          " - More than 7 letters long.\n" +
          " - No spaces.\n" +
          " - No numbers.\n" +
          " - Max 100 letters long."
      );

      console.log(introducedWord);
      break;

    default:
      break;
  }
}

function preCheckWord(introducedWord, maxLengthAllowed) {
    do {
        correctWord = false;
        correctWord = checkWord(introducedWord, maxLengthAllowed);

        if (correctWord) {
            wordsEasy.push(introducedWord);
            console.log("Palabra correcta");
        } else {
            introducedWord = prompt(
                "Error. The word is not valid. Try again:\n\n" +
                "Introduce an easy word.\n" +
                "Remember:\n" +
                " - Maximun 4 letters long.\n" +
                " - No spaces.\n" +
                " - No numbers."
            );
        }
    } while (!correctWord);
}

function checkWord(introducedWord, maxLengthAllowed) {
  let correctWord = true;
  let i = 0;

  if (introducedWord.length > maxLengthAllowed) {
    correctWord = false;
  } else {
    while (i < introducedWord.length && correctWord) {
      if (
        (introducedWord.charCodeAt(i) > 47 &&
          introducedWord.charCodeAt(i) < 58) ||
        introducedWord.trim() === ""
      ) {
        correctWord = false;
      }

      i++;
    }
  }

  return correctWord;
}

//Game code:

main();
